# Generated by Django 4.2 on 2023-04-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='average_cost',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='average_profit_per_hour',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='average_revenue',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
